Fri, 12 Mar 2021 17:43:24 connectionpool.py[line:750] WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C7547A9198>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0d8c86cf53d589438b935ff74ea818d4/timeouts
Fri, 12 Mar 2021 17:43:26 connectionpool.py[line:750] WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C7547B26D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0d8c86cf53d589438b935ff74ea818d4/timeouts
Fri, 12 Mar 2021 17:43:28 connectionpool.py[line:750] WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C7547B28D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0d8c86cf53d589438b935ff74ea818d4/timeouts
